"""initial schema

Revision ID: 2bd942ab19ce
Revises: 
Create Date: 2026-08-12 08:37:36.741471+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2bd942ab19ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appstore_notifications',
    sa.Column('notification_uuid', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=True),
    sa.Column('subtype', sa.String(length=48), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('notification_uuid', name=op.f('pk_appstore_notifications'))
    )
    op.create_table('generation_providers',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('operations', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_providers'))
    )
    op.create_table('shots_schedule',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('style_ids', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_shots_schedule'))
    )
    op.create_table('styles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('input_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('prompt_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('is_shot', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_styles'))
    )
    op.create_index('ix_styles_category', 'styles', ['category', 'sort_order'], unique=False)
    op.create_index('ix_styles_home', 'styles', ['is_home', 'sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('avatar_key', sa.Text(), nullable=True),
    sa.Column('chat_context_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_into_user_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_user_id'], ['users.id'], name=op.f('fk_users_merged_into_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_kind_last_seen', 'users', ['kind', 'last_seen_at'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_auth_identities_provider_external')
    )
    op.create_index('ix_auth_identities_user', 'auth_identities', ['user_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('thumb_key', sa.Text(), nullable=True),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_media_assets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index('ix_media_user_created', 'media_assets', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_media_user_upload_hash', 'media_assets', ['user_id', 'content_hash'], unique=True, postgresql_where=sa.text("kind = 'upload' AND deleted_at IS NULL"))
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('original_transaction_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('original_transaction_id', name=op.f('uq_subscriptions_original_transaction_id'))
    )
    op.create_index('ix_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('liked_categories', postgresql.ARRAY(sa.String(length=40)), nullable=True),
    sa.Column('disliked_categories', postgresql.ARRAY(sa.String(length=40)), nullable=True),
    sa.Column('onboarding_version', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    op.create_table('wallet_balances',
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('free_balance', sa.Integer(), nullable=False),
    sa.Column('sub_balance', sa.Integer(), nullable=False),
    sa.Column('sub_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sub_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_cap', sa.Integer(), nullable=True),
    sa.Column('last_reward_date', sa.Date(), nullable=True),
    sa.Column('reward_streak', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_balances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_wallet_balances'))
    )
    op.create_table('wallet_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('bucket', sa.String(length=8), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_ledger_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_ledger')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_wallet_ledger_idempotency_key'))
    )
    op.create_index('ix_wallet_ledger_user_created', 'wallet_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('style_id', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=48), nullable=True),
    sa.Column('provider_model', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_media_id', sa.String(length=48), nullable=True),
    sa.Column('mask_media_id', sa.String(length=48), nullable=True),
    sa.Column('result_media_id', sa.String(length=48), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.String(length=48), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mask_media_id'], ['media_assets.id'], name=op.f('fk_generations_mask_media_id_media_assets')),
    sa.ForeignKeyConstraint(['provider_id'], ['generation_providers.id'], name=op.f('fk_generations_provider_id_generation_providers')),
    sa.ForeignKeyConstraint(['result_media_id'], ['media_assets.id'], name=op.f('fk_generations_result_media_id_media_assets')),
    sa.ForeignKeyConstraint(['source_media_id'], ['media_assets.id'], name=op.f('fk_generations_source_media_id_media_assets')),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], name=op.f('fk_generations_style_id_styles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generations')),
    sa.UniqueConstraint('share_id', name=op.f('uq_generations_share_id'))
    )
    op.create_index('ix_generations_status', 'generations', ['status'], unique=False, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_index('ix_generations_user_created', 'generations', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_generations_user_op_created', 'generations', ['user_id', 'operation', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('generation_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_chat_messages_generation_id_generations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_generations_user_op_created', table_name='generations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_generations_user_created', table_name='generations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_generations_status', table_name='generations', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_table('generations')
    op.drop_index('ix_wallet_ledger_user_created', table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_table('wallet_balances')
    op.drop_table('user_preferences')
    op.drop_index('ix_subscriptions_user', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('uq_media_user_upload_hash', table_name='media_assets', postgresql_where=sa.text("kind = 'upload' AND deleted_at IS NULL"))
    op.drop_index('ix_media_user_created', table_name='media_assets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('media_assets')
    op.drop_index('ix_auth_identities_user', table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('ix_users_kind_last_seen', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_styles_home', table_name='styles')
    op.drop_index('ix_styles_category', table_name='styles')
    op.drop_table('styles')
    op.drop_table('shots_schedule')
    op.drop_table('generation_providers')
    op.drop_table('appstore_notifications')
    # ### end Alembic commands ###
