"""subscription plans and quota anchor

Revision ID: a096378524b3
Revises: 2bd942ab19ce
Create Date: 2026-08-12 09:13:53.250301+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a096378524b3'
down_revision: Union[str, None] = '2bd942ab19ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('billing_period', sa.String(length=16), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('weekly_quota', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('product_id', name=op.f('uq_subscription_plans_product_id'))
    )
    op.add_column('subscriptions', sa.Column('plan_id', sa.String(length=64), nullable=True))
    op.add_column('subscriptions', sa.Column('quota_anchor_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_subscriptions_plan_id_subscription_plans'), 'subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscriptions_plan_id_subscription_plans'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'quota_anchor_at')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
